name: s4-hana-trial
services:
    abap-platform-trial:
        stop_grace_period: 3600s
        stdin_open: true
        container_name: a4h
        hostname: vhcala4hci
        network_mode: host
        sysctls:
            - kernel.shmmax=21474836480
            - kernel.shmmni=32768
            - kernel.shmall=5242880
            - kernel.msgmni=1024
            - kernel.sem=1250 256000 100 8192
        ulimits:
            nofile:
                soft: 1048576
                hard: 1048576
        volumes:
            - /opt/s4-hana-trial/ASABAP_license:/opt/sap/ASABAP_license
            - /opt/s4-hana-trial/HDB_license:/opt/sap/HDB_license
        image: sapse/abap-cloud-developer-trial:ABAPTRIAL_2022_SP01
        command: -agree-to-sap-license -skip-limits-check